version: "1.0"
projectName: Web_Portal_FlowsProject
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: fld_111470798_stage00.projects.fl4e265f1f90c24914bc5f3126c2f61e59.integrations:FP_X12_850_To_JSON
    type: flow
    stepId: /6
    reference: fld_111470798_stage00.projects.fl4e265f1f90c24914bc5f3126c2f61e59.WmPackageServiceProvider.project.web_portal_flows.integrations:X12_850_ToJson
